services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
    ports:
      - "5432:5432"
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql